# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2cda616f3bfb3bb3d2c1475543215a9bd744acb7cbc102c42c1eb2003766bea4e4d5119626442e53de44606c886f01c2000c2e8114f7f3bf123622ee8c65f48

test:
  secret_key_base: 85340f00aad787bcc456c9b7aa28488f59e66f147ccd0af322056ea664b27a673eb8bcb5089bf9e14541092106c6c3234b6c1e2090de43664d5eaa61c341b0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
